### ISSUE TITLE
Redsys doesn't update payment_processor_id field in civicrm_financial_trxn table

### ISSUE THREAD

**Issue by helenagarcia90** [ixiam/com.ixiam.payment.redsys#15]
When a new contribution is made in the Redsys Payment Processor, civicrm_financial_trxn table is updated but payment_processor_id field does not, so there's no way to know which payment processor has been used.

**Comment by ixiam** [comment]
Hello @helenagarcia90 , could you please send us which CiviCRM version are you using?

Thanks

**Comment by francescbassas** [comment]
@helenagarcia90 if you are using a 4.7.x maybe could be related with this issue https://github.com/ixiam/com.ixiam.payment.redsys/issues/17

**Comment by sluc23** [comment]
old issue
