### ISSUE TITLE
Payment.patched.php

### ISSUE THREAD

**Issue by francescbassas** [ixiam/com.ixiam.payment.redsys#16]
What is the purpose of this file? Can be removed?

[com.ixiam.payment.redsys/CRM/Core/Payment.patched.php](https://github.com/ixiam/com.ixiam.payment.redsys/blob/1.6/CRM/Core/Payment.patched.php)

**Comment by ixiam** [comment]
This file is a patch in case you are using CiviCRM < 4.4.5, due to a core bug fixed in that release
https://github.com/ixiam/com.ixiam.payment.redsys#requirements

If you are using a greater version you can remove that file
