### ISSUE TITLE
Recurring Payment

### ISSUE THREAD

**Issue by rahilwazir** [ixiam/com.ixiam.payment.redsys#19]
My issue is not related to this project or CiviCRM. I just wanna ask you about what parameters needs to be send when doing a recurring payment (monthly subscription) with redsys? As there is very little info in the internet about this gateway

What I've currently following for recurring on initial request:
```
$args['Ds_Merchant_TransactionType'] = 5;
$args['DS_MERCHANT_DATEFREQUENCY'] = 30;
$args['Ds_Merchant_ChargeExpiryDate'] = '2016-12-21';
```

Basically my procedure currently works for basic payment but when I try with above parameters redsys outputs error saying (Offsite ofcourse)

> Data error. Contact the merchant.

Any help would be really helpful. Sorry for opening an off-topic issue.

**Comment by ixiam** [comment]
@rahilwazir sorry but we haven't used recurring contributions with Redsys. Not sure how to be configured to do so. You should contact Redsys technical support (if any..) to discuss this

Closing the issue to be off-topic
good luck
