### ISSUE TITLE
Some errors in drupal log

### ISSUE THREAD

**Issue by dragonjon** [ixiam/com.ixiam.payment.redsys#22]
It's a debugging warning I do not know if it will matter

Strict warning: Declaration of CRM_Core_Payment_Redsys::singleton() should be compatible with & CRM_Core_Payment::singleton($mode, &$paymentProcessor, &$paymentForm = NULL, $force = false) en CRM_Core_Payment::singleton() (línea 115 de /public_html/sites/all/modules/civicrm/CRM/Core/Payment.php).

Thanks

**Comment by ixiam** [comment]
Hi @dragonjon , which version of CiviCRM are you using?

**Comment by ixiam** [comment]
Hi @dragonjon , which version of CiviCRM are you using?

**Comment by dragonjon** [comment]
4.5.8

**Comment by ixiam** [comment]
Correct, functions declaration are not the same, but because last 2 params are not used in Redsys, doesn't affect the system.
We can correct this minor warning in further releases.

Thanks

**Comment by dragonjon** [comment]
Perfect, thanks for your work
