### ISSUE TITLE
Exception: API error: Could not delete payment processor type

### ISSUE THREAD

**Issue by dragonjon** [ixiam/com.ixiam.payment.redsys#24]
I use Drupal 7.54 and Civicrm 4.5.8 and the version 1.7 module.
When I enable some module in drupal or I perform some operation in the page of extensions of CIVI I get the general error "Could not delete payment processor"
In the Drupal log I get the following 2 messages:
1) Exception: API error: Could not delete payment processor type in CRM_Core_ManagedEntities-> onApiError () (line 396 of /home/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php).
2) $ ManagedEntities_failed = Array ([entity] => PaymentProcessorType [action] => delete [params] => Array ([version] => 3 [id] => 15) [result] => Array ([is_error] = > 1 [error_message] => Could not delete payment processor type))

The second message also appears in the CIVIcrm log in another format:

May 29 12:45:03 [info] $ ManagedEntities_failed = Array
(
    [Entity] => PaymentProcessorType
    [Action] => delete
    [Params] => Array
        (
            [Version] => 3
            [Id] => 15
        )

    [Result] => Array
        (
            [Is_error] => 1
            [Error_message] => Could not delete payment processor type
        )

)

The ID = 15 corresponds to the module I have reviewed in the database.

I have not tried to delete the module or anything, since we are using it in production. Where can I undo that command given to the API to delete that type of payment processor.

Thanks in advance and good work
Jon

**Comment by rubofvil** [comment]
Hi Jon

Initially we used the hook hook_civicrm_managed, in the last versions we create the payment processor with the api, and is not required the entity generated with this hook.

I think that if you remove the entity in the table(db) civicrm_managed, will be fixed this issue.


Regards

**Comment by dragonjon** [comment]
Hi Ruben @rubofvil ,
I have deleted the registry in that civicrm database table and there are no longer any error messages in either civicrm or drupal.
Thank you very much and good work
Jon
