### ISSUE TITLE
Mcrypt extension removed on PHP 7.2

### ISSUE THREAD

**Issue by francescbassas** [ixiam/com.ixiam.payment.redsys#25]
As you can see on http://php.net/releases/7_2_0.php mcrypt extension required to work with RedsysAPI is removed on PHP 7.2.

I propose:
1. Report this situation in the extensions requirement
2. Go planning on how to make the extension compatible in future versions of PHP.

**Comment by francescbassas** [comment]
Similiar here https://github.com/jesusangel/wc-sermepa/pull/34

**Comment by sluc23** [comment]
ok, good to have in mind but now a days CiviCRM 4.7 is not yet compatible with php 7.2 (nor 7.1 fully).

tx for reporting, but we'll hold this ticket for now

**Comment by francescbassas** [comment]
Related: [What to do with “mcrypt” message after upgrading to PHP 7.2](https://civicrm.stackexchange.com/questions/25769/what-to-do-with-mcrypt-message-after-upgrading-to-php-7-2)

**Comment by francescbassas** [comment]
PHP 7.2 it is already a compatible and recommended version for CiviCRM 5.x. @sluc23 maybe it's time to take this into consideration again.

**Comment by francescbassas** [comment]
PHP 7.1 Security Support Until 1 Dec 2019.

**Comment by francescbassas** [comment]
May be addressed at the same time as the https://github.com/ixiam/com.ixiam.payment.redsys/issues/34

**Comment by sluc23** [comment]
mcrypt replaced in `master` branch. @francescbassas could you test it? tx

**Comment by francescbassas** [comment]
Thanks! I have recently upgraded to version 2.2.0 and payments are still entering correctly.
