### ISSUE TITLE
Payment Method not recorded

### ISSUE THREAD

**Issue by francescbassas** [ixiam/com.ixiam.payment.redsys#33]
We are having problems with Redsys Payment Processor that is not recording correctly the Payment Method and makes hard to indentify payments from this payment processor.

![payment-method](https://user-images.githubusercontent.com/1064675/53486686-b39f4180-3a89-11e9-8d2e-28168f11725a.png)

CiviCRM 5.10.3
Redsys Payment Processor 2.1

**Comment by francescbassas** [comment]
Comented with @rubofvil but he has unable to reproduce.

**Comment by francescbassas** [comment]
This it happens only with one of the instances and we have not been able to catch the error it for a few months.. We have had problems also with webform and deadlocks caused by the [smart group rebuild cronjob](https://docs.civicrm.org/user/en/latest/initial-set-up/scheduled-jobs/#job_group_rebuild) and finally we disabled this task. Maybe they were related problems. Closing the issue at the moment.

**Comment by francescbassas** [comment]
I think I already know what the problem is.

After observing the behavior of different CiviCRM instances in which we used the Redsys payment processor, I have noticed that the problem occurs in those where we have more than one payment processor activated as a payment method.

For example, when Redsys and Paypal both are enabled. Paypal payments are well recorded when the Redsys payments does not.

@rubofvil can you confirm in a client that uses two methods of payment on a payment form that my suspicions are correct?

**Comment by francescbassas** [comment]
Ammending some registers on `civicrm_contribution` and `civicrm_financial_trxn` tables I can note that this issue happens since 2.0 release, probably after this commit https://github.com/ixiam/com.ixiam.payment.redsys/commit/2e0f316ea0c4990c0f1f254f5331b344eab30ba8

**Comment by sluc23** [comment]
Hello,

We have moved the project space for Redsys extension to CiviCRM's Gitlab.
All issues have been migrated to: https://lab.civicrm.org/extensions/redsys/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
