### ISSUE TITLE
Adapting to new 3DS2

### ISSUE THREAD

**Issue by francescbassas** [ixiam/com.ixiam.payment.redsys#34]
We recently receive a notice from the bank informing about a new protocol for the payment processor authentication. They encourage us to use it to improve the payment experience for our donors.

I leave below relevant information from a technical point of view we have received:

**Com adapto la meva eCommerce a 3DS2?**

Posem a la teva disposició els següents manuals tècnics per facilitar l'adaptació a 3DS2 al teu eCommerce:

- **Guia actualitzada d'integració Redireccion** (pots descarregar sempre l'última versió des d'aquest [Link](https://comerciagp.my.salesforce.com/sfc/p/#1r000001pXq9/a/1r000000Y3VR/ENESTGsVp1wttZmNoES5rGy3Ws_XdmOp2X9EKA288RM))
- **"Guia PSD2 - migració 3DS2"** (pots descarregar sempre l'última versió des d'aquest [Link](https://comerciagp.my.salesforce.com/sfc/p/#1r000001pXq9/a/1r000000Y3VM/h4xwDCmL2rPcc32.5kC4RPv2p1HsfxoF5.abrlsfz5M))

**Comment by sluc23** [comment]
Hello,

We have moved the project space for Redsys extension to CiviCRM's Gitlab.
All issues have been migrated to: https://lab.civicrm.org/extensions/redsys/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
