### ISSUE TITLE
Where are other versions after 1.7??

### ISSUE THREAD

**Issue by dragonjon** [ixiam/com.ixiam.payment.redsys#36]
Where are other versions after 1.7??

Thanks in advanced

**Comment by sluc23** [comment]
what do you mean @dragonjon ? You can get all the version from this git repo. They are properly tagged: 
https://github.com/ixiam/com.ixiam.payment.redsys/tags

**Comment by dragonjon** [comment]
Sorry for not finding them, I usually look for them in releases.
Sorry again and thanks for the work
