### ISSUE TITLE
Warning: Declaration of CRM_Core_Payment_RedsysIPN::validateData($paymentProcessor ...

### ISSUE THREAD

**Issue by francescbassas** [ixiam/com.ixiam.payment.redsys#37]
A warning is being recorded to the log for every Redsys transaction

> Warning: Declaration of CRM_Core_Payment_RedsysIPN::validateData($paymentProcessor, &$input, &$ids, &$objects, $required = true, $paymentProcessorID = NULL) should be compatible with CRM_Core_Payment_BaseIPN::validateData(&$input, &$ids, &$objects, $required = true, $paymentProcessorID = NULL) a require_once() (línia 3 de (...)/com.ixiam.payment.redsys/CRM/Core/Payment/RedsysIPN.php).

**Comment by sluc23** [comment]
Hello,

We have moved the project space for Redsys extension to CiviCRM's Gitlab.
All issues have been migrated to: https://lab.civicrm.org/extensions/redsys/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
