### ISSUE TITLE
Bizum integration

### ISSUE THREAD

**Issue by francescbassas** [ixiam/com.ixiam.payment.redsys#39]
Redsys allows Bizum payment integration. It would be nice to enable this integration within the CiviCRM Redsys Payment Processor.

**Comment by sluc23** [comment]
sounds an interesting integration. We would some funding in order to develop this new functionality

**Comment by sluc23** [comment]
Hello,

We have moved the project space for Redsys extension to CiviCRM's Gitlab.
All issues have been migrated to: https://lab.civicrm.org/extensions/redsys/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
