### ISSUE TITLE
Update of extension

### ISSUE THREAD

**Issue by dragonjon** [ixiam/com.ixiam.payment.redsys#4]
is planned upgrade of this extension??

Thanks

**Comment by ixiam** [comment]
Hi @dragonjon , what kind of upgrade are you meaning?

**Comment by dragonjon** [comment]
Redsys has changed the encryption to operate. Since November 23 is not accepted at old encryption.

**Comment by ixiam** [comment]
Yes, we are working on this upgrade. We don't have an ETA yet but will release it soon. Thanks for the post!

**Comment by ixiam** [comment]
v1.2 released

**Comment by dragonjon** [comment]
Many thanks for your work.
Cheers
