### ISSUE TITLE
Update deprecated function doTransferCheckout() to doPayment()

### ISSUE THREAD

**Issue by francescbassas** [ixiam/com.ixiam.payment.redsys#40]
As it says here https://github.com/civicrm/civicrm-core/blob/b633bc53df3abb9625820ebb037f0f08d67ccca5/CRM/Core/Payment.php#L1206

> Any processor that still implements the deprecated doTransferCheckout() or doDirectPayment() should be updated to use doPayment().

I do not know if this may be causing some erroneous behaviors in the extension

**Comment by sluc23** [comment]
noted @francescbassas , for this upgrade we would need to get some funding for the development and testing on different CiviCRM versions, to assure back-compatibily .

**Comment by sluc23** [comment]
Hello,

We have moved the project space for Redsys extension to CiviCRM's Gitlab.
All issues have been migrated to: https://lab.civicrm.org/extensions/redsys/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
