### ISSUE TITLE
DS_MERCHANT_TERMINAL non configurable

### ISSUE THREAD

**Issue by francescbassas** [ixiam/com.ixiam.payment.redsys#6]
I configured recently a payment processor with "la Caixa" and they give me a DS_MERCHANT_TERMINAL = 2

This is different that the value hardcoded in the extension. It can patch as a temporary solution changing the value in [CRM/Core/Payment/Redsys.php](https://github.com/ixiam/com.ixiam.payment.redsys/blob/master/CRM/Core/Payment/Redsys.php#L148) file at line 148

`$miObj->setParameter("DS_MERCHANT_TERMINAL",1);`

But it would be great if it could parameterize this value.

**Comment by ixiam** [comment]
ok, we are planning to launch a new version soon, so we could include this enhancement in there. 
My only concern is where we can add this setting. If it can be included within the Payment Processor Admin page, would be easy to implement, if not a config text file could be another easy option. But the second will nedd to be changed manually if the value si <> 1.

If a custom Page is needed to add this setting, that makes the development more complex.

**Comment by francescbassas** [comment]
Great. If you choose the config text file please note that be compatible to multisite installations.

**Comment by ixiam** [comment]
After doing some research I think the best solution for this issue is to create a Redsys settings page, to configure all these variables per CiviCRM instance.
This development could take 4-6hrs, @francescbassas  in case you can get some fundings for this we can developo it.

**Comment by francescbassas** [comment]
I'm going to work on it.

**Comment by francescbassas** [comment]
It was easier than I thought thanks to the work done previously by @elcapo. See the corresponding PR https://help.github.com/articles/creating-a-pull-request/.

**Comment by ixiam** [comment]
thanks @francescbassas , new version release 1.6
